### PR TITLE
export `build_error` symbol if RUST_BUILD_ASSERT_DENY is not set

### LINKED ISSUE #755: modpost: "build_error" undefined
When I enable `GPIO_PL061_RUST` and build this module, it shows error:

`ERROR: modpost: "build_error" [drivers/gpio/gpio_pl061_rust.ko] undefined!`

I found that functions like `IoMem::readl()` will call `IoMem::check_offset()`, which then calls `build_assert!()` and finally reaches `build_assert!()` and `build_error()`. How can I fix this?

### PR DESCRIPTION
**Pull request by nbdd0121**
This ensures that under `RUST_BUILD_ASSERT_WARN` or `RUST_BUILD_ASSERT_ALLOW`, modpost will not reject modules containing call to `rust_build_error`.

Also contains a tweak to ensure that `check_offset` is more likely to be inlined.

Should fix #755. @SocialistDalao can you check if `GPIO_PL061_RUST` build with these changes?

### CODE REVIEW

**Comment by SocialistDalao** [comment]
Thx a lot! I'll check that later. Quite busy today, sorry. If it works fine, I'll reply immediately.

By the way, I want to ask why `check_offset` is not inline while I think that it is designed to be?  Does this mean it contains bug, or it is OK that the compiler doesn't make it inline?

File: rust/build_error.rs [hunk 1]
```diff
@@ -17,13 +17,13 @@
 /// Panics if executed in const context, or triggers a build error if not.
 #[inline(never)]
 #[cold]
-#[no_mangle]
+#[export_name = "rust_build_error"]
 #[track_caller]
 pub const fn build_error(msg: &'static str) -> ! {
```
Comment (PeterWrighten) [inline rust/build_error.rs:22]: is it better to rename "buiild error" as "rust_build_error"?

Comment (ojeda) [reply rust/build_error.rs:22]: It is intended to be used by users, so `build_error` seems better.

**Comment by SocialistDalao** [comment]
YES, the PR works for me.

**Comment by ojeda** [comment]
Thanks Gary and @SocialistDalao for checking!
