### PR TITLE
rust: module.rs: Replace unwrap() with expect()

### LINKED ISSUE #90: Change `unwrap()`s to `expect()`s in `module.rs`
Although we don't get output unless we use `-Z proc-macro-backtrace`, it is a good idea to provide some more details like we do for some of the others, e.g. in:

    fn expect_punct(it: &mut token_stream::IntoIter) -> char {
        if let TokenTree::Punct(punct) = it.next().unwrap() {
        ...

This `unwrap()` may fail if we find the end of the stream unexpectedly (because the user didn't pass the arguments that we expected).

### PR DESCRIPTION
**Pull request by Sylfrena**
Use expect() instead of unwrap() to add more details
about the error in case of a panic.

Fixes #90.

Signed-off-by: Sumera Priyadarsini <sylphrenadin@gmail.com>

### CODE REVIEW

File: rust/module.rs [hunk 1]
```diff
@@ -577,7 +577,8 @@ pub fn module(ts: TokenStream) -> TokenStream {
         ));
     }
 
-    let file = std::env::var("RUST_MODFILE").unwrap();
+    let file =
+        std::env::var("RUST_MODFILE").expect("Unable to fetch key for environmental variable");
```
Comment (ojeda) [inline rust/module.rs]: Let's give a bit more information by telling the user which variable was missing:

```suggestion
        std::env::var("RUST_MODFILE").expect("Unable to fetch RUST_MODFILE environmental variable");
```

File: rust/module.rs [hunk 2]
```diff
@@ -673,5 +674,5 @@ pub fn module(ts: TokenStream) -> TokenStream {
         params_modinfo = params_modinfo,
         generated_array_types = generated_array_types,
         initcall_section = ".initcall6.init"
-    ).parse().unwrap()
+    ).parse().expect("Unable to return formatted string")
```
Comment (ojeda) [inline rust/module.rs]: I think we can improve this message. :-) The `Result` here comes from `parse()`, i.e. we may panic here if a `LexError` happens when trying to parse the formatted string into the token stream (see `FromStr` in [`proc_macro::TokenStream`](https://doc.rust-lang.org/src/proc_macro/lib.rs.html#123-137)).

File: rust/module.rs [hunk 3]
```diff
@@ -42,7 +42,7 @@ fn expect_ident(it: &mut token_stream::IntoIter) -> String {
 }
 
 fn expect_punct(it: &mut token_stream::IntoIter) -> char {
-    if let TokenTree::Punct(punct) = it.next().unwrap() {
+    if let TokenTree::Punct(punct) = it.next().expect("Expected Punct") {
```
Comment (ojeda) [inline rust/module.rs]: It is true that we are expecting a `Punct`, but if `next()` failed here it is because we reached the end of the token stream, i.e. there is no more input in the macro. So it is different from the `panic!` below, because that one triggers when there was *some* input, but it was not the `Punct` (rather than no input at all).

If we provide a more precise message, it is easier for users to distinguish those two cases (feel free to change the `panic!` messages too if you think they can be improved!).

**Review by ojeda — COMMENTED** [review]
Thanks for the PR!

File: rust/module.rs (hunk 3 above)
Comment (ojeda) [reply rust/module.rs]: (Same for the similar other cases)

Comment (Sylfrena) [reply rust/module.rs]: I made all the changes, thanks for the feedback!

Comment (Sylfrena) [reply rust/module.rs]: oops, looks like my linter didn't catch a rustfmt error, will reopen the PR once I correct this. Sorry for the noise. :/

File: rust/module.rs [hunk 4]
```diff
@@ -673,5 +677,5 @@ pub fn module(ts: TokenStream) -> TokenStream {
         params_modinfo = params_modinfo,
         generated_array_types = generated_array_types,
         initcall_section = ".initcall6.init"
-    ).parse().unwrap()
+    ).parse().expect("LexError returned whle trying to parse the string token stream.")
```
Comment (ojeda) [inline rust/module.rs]: Typo:

```suggestion
    ).parse().expect("LexError returned while trying to parse the string token stream")
```

Also, perhaps we can just say:

    Error parsing formatted string into token stream

**Review by ojeda — CHANGES_REQUESTED** [review]

File: rust/module.rs (hunk 3 above)
Comment (ojeda) [reply rust/module.rs]: No problem at all -- the CI is intentionally quite strict, so do not worry if you need to force-push to fix things/re-run it until `clippy`, `rustfmt` and `rustdoc` are happy :-)

File: rust/module.rs (hunk 4 above)
Comment (Sylfrena) [reply rust/module.rs]: Thanks! I made the changes.

**Review by jabedude — APPROVED** [review]
LGTM!

**Review by ojeda — APPROVED** [review]

**Comment by ojeda** [comment]
Thanks a lot! :-)
