### PR TITLE
Use @file to pass the --cfg flags to rustc (fixes #22)

### LINKED ISSUE #22: Avoid using a bunch of cfg flags and use of hardcoded auto.conf path
Currently, building with O=$something fails as auto.conf is search for in the source tree.
Also the arguments passed as cfg parsed from auto.conf can get bigger as the max argument length of linux.

### PR DESCRIPTION
**Pull request by ojeda**
It also helps to avoid spamming the terminal when doing verbose builds.

Signed-off-by: Finn Behrens <me@kloenk.de>
Signed-off-by: Miguel Ojeda <ojeda@kernel.org>

### CODE REVIEW

File: scripts/kconfig/confdata.c [hunk 1]
```diff
@@ -636,6 +636,56 @@ static struct conf_printer kconfig_printer_cb =
...
+		 * To have similar functionality to the C macro `IS_ENABLED()`,
+		 * from Rust, we provide an empty `--cfg CONFIG_X` here in
+		 * both `y` and `m` cases.
+		 *
+		 * Then, the common `fprintf()` below will also give us
+		 * a `--cfg CONFIG_X="y"` or `--cfg CONFIG_X="m"`, which can
+		 * be used as the equivalent of `IS_BUILTIN()`/`IS_MODULE()`.
+		 */
+		if (*value == 'y' || *value == 'm')
+			fprintf(fp, "--cfg=%s%s\n", CONFIG_, sym->name);
```
Comment (ojeda) [inline scripts/kconfig/confdata.c:673]: @Kloenk This is the fix you needed.

File: Makefile [hunk 2]
```diff
@@ -726,7 +726,7 @@ $(KCONFIG_CONFIG):
 # This exploits the 'multi-target pattern rule' trick.
 # The syncconfig should be executed only once to make all the targets.
 # (Note: use the grouped target '&:' when we bump to GNU Make 4.3)
-%/config/auto.conf %/config/auto.conf.cmd %/generated/autoconf.h: $(KCONFIG_CONFIG)
+%/config/auto.conf %/config/auto.conf.cmd %/generated/autoconf.h %/generated/rustc_cfg: $(KCONFIG_CONFIG)
```
Comment (ojeda) [inline Makefile:729]: I changed a few of the names of several things/variables/etc. to improve clarity (hopefully!).

File: scripts/kconfig/confdata.c [hunk 3]
```diff
@@ -636,6 +636,56 @@ static struct conf_printer kconfig_printer_cb =
...
+		break;
+	}
+
+	fprintf(fp, "--cfg=%s%s=%s\n", CONFIG_, sym->name, str);
+}
+
+static struct conf_printer rustc_cfg_printer_cb =
+{
+	.print_symbol = rustc_cfg_print_symbol,
+};
```
Comment (ojeda) [inline scripts/kconfig/confdata.c:687]: No need here for the `.print_comment` function pointer, so we can take the function out too.

**Comment by ojeda** [comment]
@Kloenk Since I kept you as the author (as if I had applied your patches in my tree in a ML-based workflow), you need to confirm you agree with the changes I did on your behalf :-)

File: scripts/kconfig/confdata.c [hunk 4]
```diff
@@ -636,6 +636,56 @@ static struct conf_printer kconfig_printer_cb =
...
+		/*
+		 * We don't care about disabled ones, i.e. no need for
+		 * what otherwise are "comments" in other printers.
+		 */
+		if (*value == 'n')
+			return;
+
+		/*
+		 * To have similar functionality to the C macro `IS_ENABLED()`,
+		 * from Rust, we provide an empty `--cfg CONFIG_X` here in
```
Comment (ojeda) [inline scripts/kconfig/confdata.c]: Oops, typo, let me force push.

**Comment by kloenk** [comment]
So the difference between this and #23 is the use of build.rs right?

What's the direction we want to go with build.rs? I'm more a fan of removing it, as we only have to have bingen, and not some libclang path set.

File: scripts/Makefile.lib [hunk 5]
```diff
@@ -229,9 +229,9 @@ c_flags        = -Wp,-MMD,$(depfile) $(NOSTDINC_FLAGS) $(LINUXINCLUDE)     \
 RUST_BINDGEN_CFLAGS = $(c_flags) $(KBUILD_CFLAGS_MODULE)
 export RUST_BINDGEN_CFLAGS
 
-rustc_cfg_flags = $(shell sed -nE 's/^(CONFIG_[^=]+)=(y|m)$$/--cfg \1/p' $(srctree)/include/config/auto.conf | xargs)
+KCONFIG_RUSTC_CFG ?= $(srctree)/include/generated/rustc_cfg
 
-rustc_flags     = $(_rustc_flags) $(modkern_rustcflags) $(rustc_cfg_flags)
+rustc_flags     = $(_rustc_flags) $(modkern_rustcflags) @$(shell readlink -f $(KCONFIG_RUSTC_CFG))
```
Comment (kloenk) [inline scripts/Makefile.lib:234]: Would like to remove readlink someday, but does not have to be now

**Review by kloenk — APPROVED** [review]
LGTM, would rebase #23 to master if this gets merged.

File: scripts/kconfig/confdata.c [hunk 6]
```diff
@@ -636,6 +636,56 @@ static struct conf_printer kconfig_printer_cb =
...
+		if (*value == 'y' || *value == 'm')
+			fprintf(fp, "--cfg=%s%s\n", CONFIG_, sym->name);
+
+		break;
+	default:
+		str = value;
+		break;
+	}
+
+	fprintf(fp, "--cfg=%s%s=%s\n", CONFIG_, sym->name, str);
```
Comment (kloenk) [inline scripts/kconfig/confdata.c:681]: This creates 2 times the same CFC flag? Does it work? Is cfg!(CONFIG_C) false if X is n? Or is it set to n and so returns true?

Comment (ojeda) [reply scripts/kconfig/confdata.c:681]: Yeah, it works! `cfg` holds a multimap, which allows us to do things like this:

    #[cfg(not(CONFIG_X))]
    pub static CONFIG_X_DISABLED: i32 = 0;

    #[cfg(CONFIG_X)]
    pub static CONFIG_X_ENABLED: i32 = 0;
    
    #[cfg(CONFIG_X="y")]
    pub static CONFIG_X_BUILTIN: i32 = 0;
    
    #[cfg(CONFIG_X="m")]
    pub static CONFIG_X_MODULE: i32 = 0;

Since the most common case is checking whether `CONFIG_X` is enabled in any way (either `y` or `m`), I suggested this way in https://github.com/Rust-for-Linux/linux/issues/22#issuecomment-706620374. Thus most code gets the best looking code: `#[cfg(CONFIG_X)]`.

Another option is generating things like `CONFIG_X_ENABLED` directly instead of using just `CONFIG_X`, but I thought this mimicked best what C does, looks best for the common case and is guaranteed to not have collisions, e.g. if someone wants to define both `CONFIG_X` and `CONFIG_X_MODULE`.

**Comment by ojeda** [comment]
> So the difference between this and #23 is the use of build.rs right?

Yeah, plus your `O=...` work/fixes (i.e. they are not here; I undid them to separate the different fixes in different PRs/commits).

> What's the direction we want to go with build.rs? I'm more a fan of removing it, as we only have to have bingen, and not some libclang path set.

Let me send the PR and I'll reply to you there.

File: scripts/kconfig/confdata.c (hunk 6 above)
Comment (ojeda) [reply scripts/kconfig/confdata.c:681]: I should probably copy this example to somewhere in `Documentation/rust` too.
