### PR TITLE
rust/kernel/traits: fix rustdoc warnings

### LINKED ISSUE #307: Warnings when running `rustdoc` on `rust/kernel/traits.rs`
I'm getting the following warnings when running `make rustdoc`.

This is also visible on CI ([example here](https://github.com/Rust-for-Linux/linux/pull/305/checks?check_run_id=2689142892)), so it's not a configuration issue on my side

```
warning: unresolved link to `Box`
  --> rust/kernel/traits.rs:11:68
   |
11 | /// Common pointer types which implement a `pin()` method include [`Box`], [`Arc`] and [`Rc`].
   |                                                                    ^^^^^ no item named `Box` in scope
   |
   = note: `#[warn(broken_intra_doc_links)]` on by default
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `Rc`
  --> rust/kernel/traits.rs:11:89
   |
11 | /// Common pointer types which implement a `pin()` method include [`Box`], [`Arc`] and [`Rc`].
   |                                                                                         ^^^^ no item named `Rc` in scope
   |
   = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: 2 warnings emitted
```

@TheSven73 it looks like this was introduced by 02138fd952a65ab8b72ce55de59587de6b2b14af.

### PR DESCRIPTION
**Pull request by TheSven73**
A previous commit (Rust-for-Linux#292) introduced rustdoc warnings.
Fix rustdoc links to eliminate these warnings.

Signed-off-by: Sven Van Asbroeck <thesven73@gmail.com>

Fixes #307

### CODE REVIEW

**Comment by ksquirrel** [comment]
Review of `0a91321af87e`:
  - ✔️ Commit [`0a91321`](https://github.com/Rust-for-Linux/linux/commit/0a91321af87ee8573ade6ae9d63bda74be05b2ab): Looks fine!

**Comment by ojeda** [comment]
The `Rc` is gone, is that intended?

**Comment by TheSven73** [comment]
Yes. A quick grep through `rust/kernel` showed that we're not using `Rc` anywhere.

File: rust/kernel/traits.rs [hunk 1]
```diff
@@ -8,7 +8,7 @@ use alloc::{alloc::AllocError, sync::Arc};
 
 /// Trait which provides a fallible version of `pin()` for pointer types.
 ///
-/// Common pointer types which implement a `pin()` method include [`Box`], [`Arc`] and [`Rc`].
+/// Common pointer types which implement a `pin()` method include [`alloc::boxed::Box`] and [`Arc`].
```
Comment (bjorn3) [inline rust/kernel/traits.rs]: Maybe keep `Box` as visible name but use `alloc::boxed::Box` as link target?

Comment (ojeda) [reply rust/kernel/traits.rs]: Agreed, it would look nicer.

**Comment by ojeda** [comment]
> Yes. A quick grep through `rust/kernel` showed that we're not using `Rc` anywhere.

Thanks! In general, please mention this kind of "implicit" changes in the commit message.

File: rust/kernel/traits.rs (hunk 1 above)
Comment (TheSven73) [reply rust/kernel/traits.rs]: How does that work? Any suggestions?

**Comment by ksquirrel** [comment]
Review of `f4f353bdd5e9`:
  - ✔️ Commit [`f4f353b`](https://github.com/Rust-for-Linux/linux/commit/f4f353bdd5e99f9ea732c55132c614a828c2a345): Looks fine!

File: rust/kernel/traits.rs (hunk 1 above)
Comment (ojeda) [reply rust/kernel/traits.rs]: I think it was something like:

    [`Box`](alloc::boxed::Box)

or out-of-line:

    /// [`Box`]: alloc::boxed::Box

**Comment by TheSven73** [comment]
### v1 -> v2:
- mention in commit message that rustdoc reference to `Rc` has been removed
- keep Box as visible name but use alloc::boxed::Box as link target

File: rust/kernel/traits.rs (hunk 1 above)
Comment (TheSven73) [reply rust/kernel/traits.rs]: Luckily I guessed correctly :)
